### ISSUE TITLE
`go get`: module declares its path as: github.com/buildpack/libbuildpack

### ISSUE THREAD

**Issue by jromero** [buildpacks/libbuildpack#13]
Installing this via `go get` yields an error.

```
$ go get github.com/buildpacks/libbuildpack
go: finding github.com/buildpacks/libbuildpack v1.25.11
go: downloading github.com/buildpacks/libbuildpack v1.25.11
go: extracting github.com/buildpacks/libbuildpack v1.25.11
go get: github.com/buildpacks/libbuildpack@v1.25.11: parsing go.mod:
        module declares its path as: github.com/buildpack/libbuildpack
                but was required as: github.com/buildpacks/libbuildpack
```

Current workaround is to declare the dependency as the original name via `go get github.com/buildpack/libbuildpack`. Notice the use of singular vs plural org name.

**Comment by jromero** [comment]
This was mostly due to my naiveness. I was unaware that the latest version was v2. That said, it might be worth adding a single line for "usage" to the README.md.

```shell
go get github.com/buildpacks/libbuildpack/v2
```

**Comment by nebhale** [comment]
God love Go Modules.
